# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tf-u5EAScUC9zlUVDNBiDrWZFv4-Zm08
"""

x=10

print(x)

y=20

print x+y

x+y

x=10

type(x)

x="rohan tom davis"

type(x)

x="rohan"

y="tom davis"

x+y

x="10"
y="20"
x+y

x=input()

x

y=int(x)
y

type(x)

x=int(input())

type(x)

x=int(input("enter a number"))

type(x)

x=int(input())
  y=int(input())
  x+y

x-y

x*y

x/y

p=int(input("enter the initial principal balance"))
r=int(input("enter the annual interest rate"))
t=int(input("enter the time(in years)"))
a=p*(1+(r/100)*t)
a

p=int(input('enter principal amount'))
r=int(input('enter interest rate'))
n=int(input('enter the number of times interest is compunded per year'))
nt=int(input('enter the time(years'))
A=p*(1+r/n)**(n)*t
A

